name: Run Hello Action

on: workflow_dispatch

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run custom hello action
        uses: ./.github/actions/hello-action
